spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor
    username: root
    password: 

#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER


    jpa:
      hibernate:
        ddl-auto: create
        show-sql: true
